import os
import random
import msvcrt
import time

prof = 10
help = 1
way = 0

def welcome():
    os.system("cls")
    print("Welcome",end=" ")
    time.sleep(0.4)
    print("to",end=" ")
    time.sleep(0.4)
    print("the",end=" ")
    time.sleep(0.4)
    print("text-based",end=" ")
    time.sleep(0.4)
    print("adventure",end=" ")
    time.sleep(0.4)
    print("game",end=" ")
    time.sleep(0.4)
    os.system("cls")
    print("Starting",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    return

def about():
    os.system("cls")
    print("Hello\n")
    time.sleep(0.55)
    print("This is a text based adventure game.")
    time.sleep(0.65)
    print("Hope you like it.")
    time.sleep(0.25)
    print("^_^")
    print("\n\nPress any key to go back.")
    msvcrt.getch()
    return

def end():
    os.system("cls")
    print("T",end="")
    time.sleep(0.2)
    print("H",end="")
    time.sleep(0.2)
    print("A",end="")
    time.sleep(0.2)
    print("N",end="")
    time.sleep(0.2)
    print("K",end=" ")
    time.sleep(0.2)
    print("Y",end="")
    time.sleep(0.2)
    print("O",end="")
    time.sleep(0.2)
    print("U",end=" ")
    time.sleep(0.2)
    print("^_^",end="")
    time.sleep(1)
    exit()

def long():
    time.sleep(1.45)
def suspense():
    time.sleep(2)
def quick():
    time.sleep(0.25)
def narr():
    time.sleep(1.20)
def notice():
    time.sleep(0.85)
def dots():
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)

def scene6():
    os.system("cls")
    long()
    print("{So how am I supposed to start}\n")
    long()
    print("[Well, start investigating]\n")
    suspense()
    dots()
    print("\n")
    print("[Oh, yeah]")
    narr()
    print("[You must be so clueless, Detective Homeless]")
    narr()
    print("[Why don't you start with observing this room]\n")
    suspense()
    print("You look around\n")
    suspense()
    print("{Oh my god...}\n")
    quick()
    print("[Yess..]\n")
    narr()
    print("'Sigh'\n")
    long()
    print("{Oh come on...}")
    narr()
    print("{Maybe I forgot the exclamation mark}\n")
    long()
    print("{Oh my god!!}")
    narr()
    print("{He has a PS5}")
    suspense()
    print("{Maybe I will need that for investigative purposes}")
    suspense()
    print("{Yeah I will need that for investigation, Hehe}")
    long()
    print("{Heehee }")
    narr()
    print("{Hahaha }")
    narr()
    print("{Heeeheee }\n")
    quick()
    print("Detective Kabeer: Sir,",end=" ")
    suspense()
    print("You must have found something right.")
    suspense()
    dots()
    print("\n")
    long()
    print("Detective Kabeer: Sir..\n")
    quick()
    print("\"Yeah\"")
    long()
    print("\"Yeah,",end=" ")
    narr()
    print("working on it\"\n")
    long()
    

def scene5():
    os.system("cls")
    long()
    print("You enter the house.\n")
    long()
    print("You see a young man, his eyes darting here and there, unsetting anywhere.")
    suspense()
    print("He spots you, his eyes glimmer followed by a sense of relief in him.\n")
    suspense()
    narr()
    print("Rohit: Good Morning sir.")
    long()
    print("Rohit: Thanks for coming on my request.\n")
    suspense()
    print("{Wait..}")
    narr()
    print("{What am I supposed to do now}\n")
    narr()
    print("[Just Solve the case]\n")
    long()
    print("{\'Sigh\'}")
    notice()
    print("{You again}\n")
    suspense()
    print("\"Well, You must be Rohit\"")
    narr()
    print("\"Don't Worry, I will be taking your case from here.\"\n")
    narr()
    print("Rohit: Yeah Sir, Thanks.\n")
    narr()
    dots()
    print("\n\n{Wow!, This worked right}")
    narr()
    print("{Yeah, this is what they do in the detective movies}\n")
    long()
    print("[So you have been a detective genre fan...]\n")
    long()
    print("{I thought you knew everything}\n")
    suspense()
    print("[Well, I do know everything.]\n")
    long()
    print("{Yeah, Yeah.}\n")
    long()
    print("[You know what]\n")
    narr()
    print("{What?}\n")
    narr()
    print("[You remind me of one of your fiction detectives.]\n")
    long()
    print("{Sherlock Holmes?}\n")
    long()
    print("[No, Sherlock 'Homeless']")
    notice()
    print("[Hahaha]\n")
    long()
    dots()
    print("\n")
    narr()
    print("\n[Maybe you didn't get it...]")
    narr()
    print("['Holmes' and 'Homeless']\n")
    notice()
    print("{Come on, It was a bad joke..}\n")
    narr()
    print("Press any key to continue")
    msvcrt.getch()

def scene4():
    os.system("cls")
    long()
    print("You step out of the car.")
    long()
    print("You see a completely ordinary street.")
    suspense()
    print("In front of you, stands a house with half gates open.")
    narr()
    print("As if waiting for you.\n")
    suspense()
    long()
    print("Detective Kabeer: Sir,",end=" ")
    long()
    print("This is where we got our case.\n")
    suspense()
    print("You open the file: \n\n")
    long()
    print("Case ID : M/26/1/A")
    narr()
    print("Client: Rohit")
    long()
    print("Client Occupation: Journalist")
    long()
    print("Case: The client has claimed:")
    narr()
    print("Someone has been entering his house.")
    long()
    print("Things are moved here and there.")
    long()
    print("Door is always locked whenever he comes back.")
    suspense()
    print("There are no missing objects or any sign of robbery.\n\n")
    suspense()
    suspense()
    print("{What am I even supposed to do.}")
    narr()
    print("{Oh my god...}\n")
    quick()
    print("[Yes my child..]\n")
    suspense()
    dots()
    long()
    print("\n\n[You called for me right.]\n")
    long()
    print("{Well, I didn't expect you}")
    narr()
    print("{Anyways if you are here then help me}\n")
    long()
    print("[Simple, just solve the case.]\n")
    suspense()
    print("\'Awkward Silence\'\n")
    suspense()
    print("{In no way it was helpful}\n")
    long()
    print("[I am a angel, this is how I help.]\n")
    suspense()
    print("{Yeah figured it out.}")
    long()
    print("Press any key to continue")
    msvcrt.getch()
    scene5()

def scene3a():
    os.system("cls")
    narr()
    print("You chose to sleep.")
    narr()
    os.system("cls")
    dots()
    os.system("cls")
    dots()
    os.system("cls")
    long()
    print("Detective Kabeer: Sir")
    long()
    print("Detective Kabeer: Sir\n")
    quick()
    print("You wake up with a snap.\n")
    long()
    print("Sir, You must be tired but we have reached our destination.\n")
    narr()
    print("\"Lets Go.\"\n")
    long()
    print("Press any key to continue.")
    narr()
    msvcrt.getch().decode()
    scene4()

def scene3b():
    os.system("cls")
    narr()
    print("You chose to observe things around you.\n")
    global way
    way = 1
    suspense()
    print("You see the way all over.")
    narr()
    print("Bustling Roads.")
    long()
    print("Children playing with innocense, unaware of what lies ahead in their life.")
    suspense()
    print("The drive was ordinary, but astonishingly calm.\n")
    suspense()
    print("{Maybe I am still in the process of accepting what's happening with me}\n")
    suspense()
    print("The car slows to a halt.\n")
    long()
    print("Detective Kabeer: Sir,",end=" ")
    narr()
    print("We have reached.")
    narr()
    print("\"Yeah, Lets go.\"\n")
    print("Press any key to continue.")
    msvcrt.getch()
    scene4()

def scene3():
    os.system("cls")
    long()
    print("He takes you to his car.")
    narr()
    print("His car was not flashy,",end=" ")
    narr()
    print("A plain white sedan, simple and steady like him.\n")
    suspense()
    print("Chose your option: ")
    print("a) Save your Energy and sleep.")
    print("b) Stay Awake and observe things...")
    ch=msvcrt.getch().decode()
    while ch!="a" and ch!="b":
        print("Enter a valid option(a, b)")
        narr()
        ch = msvcrt.getch().decode()
    if ch=="a":
        scene3a()
    if ch=="b":
        scene3b()        

def scene2a():
    os.system("cls")
    long()
    print("His eyes narrowed,",end=" ")
    narr()
    print("a faint smile,",end=" ")
    narr()
    print("followed by a nod.\n")
    long()
    print("You follow him.\n")
    narr()
    print("{For now I need to go on with this life.}")
    narr()
    print("{Lets see what lies ahead.}")
    suspense()
    print("Press any key to continue.")
    msvcrt.getch()
    scene3()

def scene2b():
    os.system("cls")
    narr()
    print("His eyes widened briefly,",end=" ")
    narr()
    print("acknowledged with quiet regard.")
    long()
    print("Like he didn't expected this response.\n")
    suspense()
    print("Detective Kabeer: But sir.\n")
    narr()
    print("\"Okaay \"")
    narr()
    print("\"Let's Go.\"\n")
    long()
    print("You follow him.")
    narr()
    print("{Lets see what more lies ahead till I am stuck in this body}\n")
    suspense()
    print("Press any key to continue.")
    msvcrt.getch()
    scene3

def scene2():
    os.system("cls")
    notice()
    print("Behind you,",end=" ")
    long()
    print("the door is opening slowly.")
    suspense()
    print("From the opening door comes light,",end=" ")
    suspense()
    print("breaking the darkness in the room.")
    long()
    print("Followed by a middle-aged man, queit and steady.")
    long()
    narr()
    print("His eyes silently expecting you to understand something.")
    suspense()
    dots()
    long()
    print("\nDetective Kabir: Sir",end=" ")
    long()
    print("We got ourself a new case.",end=" ")
    narr()
    print("Lets Go.\n")
    long()
    print("{I needed a lot of answers from the guardian angel.}\n")
    narr()
    print("Chose your response: ")
    print("a) Yeah, Lets GO.")
    print("b) Whatever, we will do it later.")
    ch=msvcrt.getch().decode()
    while ch!="a" and ch!="b":
        narr()
        print("Chose a valid option(a, b)")
        ch=msvcrt.getch().decode()
    if ch=="a":
        print("\"Yeah,",end=" ")
        notice()
        print("Lets Go.\"")
        long()
        scene2a()
    if ch=="b":
        print("\"What\"")
        narr()
        print("\"Whatever,",end=" ")
        narr()
        print("I ain't going anywhere right now.\"")
        long()
        global prof
        prof = prof - 1
        scene2b()

def scene1a():
    os.system("cls")
    long()
    print("\"I really don't have any choice right.\"")
    suspense()
    print("\"So, yeah here I am, you must have many things to tell me right.\"\n")
    suspense()
    print("[Yeah, it's good to see you have accepted your fate.]")
    suspense()
    print("[There's a reason you are reincarnated in this body.]")
    suspense()
    print("[The reason being]\n")
    quick()
    print("..clink..")
    long()
    print("..clank..\n")
    notice()
    print("You look behind.")
    suspense()
    print("The door behind you is opening.\n")
    long()
    print("Press any key to continue.")
    msvcrt.getch()
    scene2()
    os.system("cls")
    long()

def scene1b():
    os.system("cls")
    narr()
    print("\"How do you even think that I am gonna agree to it.\"")
    long()
    print("\"Whatever it is, I don't care just give me back my normal life.\"\n")
    suspense()
    print("\"Hello!!\"\n")
    suspense()
    dots()
    long()
    print("\nThe guardian angel doesn't seem to like it.")
    narr()
    print("Try to keep him happy, he may be very helpful.")
    long()
    global help
    help = help - 1
    narr()
    print("\n[Well...]")
    suspense()
    print("[You are the dumb rebellious kind of kid.]")
    suspense()
    print("[Whatever, I am supposed to do my work here.]")
    suspense()
    print("[What I was gonna say is that]\n")
    narr()
    print("..clink...")
    long()
    print("..clank...")
    notice()
    print("A door behind you opens...")
    narr()
    print("You look back.")
    suspense()
    print("Press any key to continue.\n")
    msvcrt.getch()
    os.system("cls")
    long()
    scene2()

def scene1c():
    os.system("cls")
    narr()
    print("{Oh! I don't think it's good to be rebellious here.}\n")
    long()
    print("{Maybe I should just play along}")
    long()
    print("As you say sir...")
    long()
    print("Excuse Me, If I unknowingly caused you any inconvenience.\n")
    suspense()
    print("The Guardian Angel seems impressed.")
    global help
    help = help+1
    narr()
    print("You might get his help later if you keep him impressed.\n")
    narr()
    print("[Uhmm..]")
    narr()
    print("[Uhmm..]")
    long()
    print("[Enough of the flattery.]")
    long()
    print("[So I was telling you that]")
    quick()
    print("..clunk..")
    suspense()
    print("..creak..\n")
    narr()
    print("A door opens behind you")
    notice()
    print("You look back")
    narr()
    print("Press any key to continue..")
    msvcrt.getch()
    os.system("cls")
    long()
    scene2()

def scene1():
    os.system("cls")
    print("darkness",end="")
    dots()
    os.system("cls")
    time.sleep(0.85)
    print("THUD")
    long()
    print("You fall from your bed...")
    narr()
    print("You wake up and realise something",end=" ")
    narr()
    print("\"This is not my room.\"")
    long()
    print("You get up and notice something")
    notice()
    print("You are wearing a long brown coat")
    long()
    print("You check your pockets")
    long()
    dots()
    quick()
    print("You found a pen, a notebook, a badge.")
    long()
    print("Press e to interact with the badge")
    choice=msvcrt.getch().decode()
    if choice=="e":
        os.system("cls")
        time.sleep(0.45)
        print("You see the badge.")
        narr()
        print("The badge reads: Detective Mehul - Private Detective")
        long()
    else:
        print("You chose to ignore the badge.\n")
        long()
    
    print("\"What is this happening...\"\n")
    narr()
    print("A strange voice suddenly  fills the room.\n")
    narr()
    print("[Getting normal, are you?]")
    long()
    print("\"What!!\"\n")
    suspense()
    dots()
    dots()
    suspense()
    print("\"Is this game lagging\"\n")
    quick()
    print("[Absolutely Not!]")
    long()
    print("[Come on, It was just a dramatical pause.]")
    long()
    print("[By the way, treat me with some respect]")
    long()
    print("[I am your guardian angel.]\n")
    suspense()
    print("\"Am I dreaming..\"")
    quick()
    print("[Absolutely Not, You have been reincarnated as detective Mehul.]\n")
    suspense()
    print("\"Whatt!!, Why??")
    narr()
    print("[You really think you have a choice]\n")
    quick()
    print("\"Why don't I have one?\"")
    suspense()
    print("[Come on, Just Accept It.]\n\n")
    narr()
    print("Press any key to continue.")
    msvcrt.getch()
    print("Chose one Option: ")
    print("a) \"I really don't seem to have any choice...\"")
    print("b) \"How do you even think I am gonna agree to it...\"")
    print("c) \"As you say Sir...\"")
    time.sleep(0.25)
    ch1=msvcrt.getch().decode()
    while ch1!="a" and ch1!="b" and ch1!="c":
        print("Chose from the options(a,b,c).")
        time.sleep(0.15)
        ch1=msvcrt.getch().decode()
    
    if ch1=="a":
        long()
        scene1a()
    if ch1=="b":
        long()
        scene1b()
    if ch1=="c":
        long()
        scene1c()

scene6()

