import os
import random
import msvcrt
import time

prof = 10
help = 1

def welcome():
    os.system("cls")
    print("Welcome",end=" ")
    time.sleep(0.4)
    print("to",end=" ")
    time.sleep(0.4)
    print("the",end=" ")
    time.sleep(0.4)
    print("text-based",end=" ")
    time.sleep(0.4)
    print("adventure",end=" ")
    time.sleep(0.4)
    print("game",end=" ")
    time.sleep(0.4)
    os.system("cls")
    print("Starting",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    print(".",end="")
    time.sleep(0.2)
    return

def about():
    os.system("cls")
    print("Hello\n")
    time.sleep(0.55)
    print("This is a text based adventure game.")
    time.sleep(0.65)
    print("Hope you like it.")
    time.sleep(0.25)
    print("^_^")
    print("\n\nPress any key to go back.")
    msvcrt.getch()
    return

def end():
    os.system("cls")
    print("T",end="")
    time.sleep(0.2)
    print("H",end="")
    time.sleep(0.2)
    print("A",end="")
    time.sleep(0.2)
    print("N",end="")
    time.sleep(0.2)
    print("K",end=" ")
    time.sleep(0.2)
    print("Y",end="")
    time.sleep(0.2)
    print("O",end="")
    time.sleep(0.2)
    print("U",end=" ")
    time.sleep(0.2)
    print("^_^",end="")
    time.sleep(1)
    exit()

def long():
    time.sleep(1.45)
def suspense():
    time.sleep(2)
def quick():
    time.sleep(0.25)
def narr():
    time.sleep(1.20)
def notice():
    time.sleep(0.85)

def dots():
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)
    print(".",end="")
    time.sleep(0.35)

def scene3():
    os.system("cls")

def scene2a():
    os.system("cls")
    long()
    print("His eyes narrowed,",end=" ")
    narr()
    print("a faint smile,",end=" ")
    narr()
    print("followed by a nod.\n")
    long()
    print("You follow him.\n")
    narr()
    print("{For now I need to go on with this life.}")
    narr()
    print("{Lets see what lies ahead.}")
    suspense()
    print("Press any key to continue.")
    msvcrt.getch()
    scene3()

def scene2b():
    os.system("cls")
    narr()
    print("His eyes widened briefly,",end=" ")
    narr()
    print("acknowledged with quiet regard.")
    long()
    print("Like he didn't expected this response.\n")
    suspense()
    print("Detective Kabeer: But sir.\n")
    narr()
    print("\"Okaay \"")
    narr()
    print("\"Let's Go.\"\n")
    long()
    print("You follow him.")
    narr()
    print("{Lets see what more lies ahead till I am stuck in this body}\n")
    suspense()
    print("Press any key to continue.")
    msvcrt.getch()
    scene3

def scene2():
    os.system("cls")
    notice()
    print("Behind you,",end=" ")
    long()
    print("the door is opening slowly.")
    suspense()
    print("From the opening door comes light,",end=" ")
    suspense()
    print("breaking the darkness in the room.")
    long()
    print("Followed by a middle-aged man, queit and steady.")
    long()
    narr()
    print("His eyes silently expecting you to understand something.")
    suspense()
    dots()
    long()
    print("\nDetective Kabir: Sir",end=" ")
    long()
    print("We got ourself a new case.",end=" ")
    narr()
    print("Lets Go.\n")
    long()
    print("{I needed a lot of answers from the guardian angel.}\n")
    narr()
    print("Chose your response: ")
    print("a) Yeah, Lets GO.")
    print("b) Whatever, we will do it later.")
    ch=msvcrt.getch().decode()
    while ch!="a" and ch!="b":
        narr()
        print("Chose a valid option(a, b)")
        ch=msvcrt.getch().decode()
    if ch=="a":
        print("\"Yeah,",end=" ")
        notice()
        print("Lets Go.\"")
        long()
        scene2a()
    if ch=="b":
        print("\"What\"")
        narr()
        print("\"Whatever,",end=" ")
        narr()
        print("I ain't going anywhere right now.\"")
        long()
        global prof
        prof = prof - 1
        scene2b()

def scene1a():
    os.system("cls")
    long()
    print("\"I really don't have any choice right.\"")
    suspense()
    print("\"So, yeah here I am, you must have many things to tell me right.\"\n")
    suspense()
    print("[Yeah, it's good to see you have accepted your fate.]")
    suspense()
    print("[There's a reason you are reincarnated in this body.]")
    suspense()
    print("[The reason being]\n")
    quick()
    print("..clink..")
    long()
    print("..clank..\n")
    notice()
    print("You look behind.")
    suspense()
    print("The door behind you is opening.\n")
    long()
    print("Press any key to continue.")
    msvcrt.getch()
    scene2()
    os.system("cls")
    long()

def scene1b():
    os.system("cls")
    narr()
    print("\"How do you even think that I am gonna agree to it.\"")
    long()
    print("\"Whatever it is, I don't care just give me back my normal life.\"\n")
    suspense()
    print("\"Hello!!\"\n")
    suspense()
    dots()
    long()
    print("\nThe guardian angel doesn't seem to like it.")
    narr()
    print("Try to keep him happy, he may be very helpful.")
    long()
    global help
    help = help - 1
    narr()
    print("\n[Well...]")
    suspense()
    print("[You are the dumb rebellious kind of kid.]")
    suspense()
    print("[Whatever, I am supposed to do my work here.]")
    suspense()
    print("[What I was gonna say is that]\n")
    narr()
    print("..clink...")
    long()
    print("..clank...")
    notice()
    print("A door behind you opens...")
    narr()
    print("You look back.")
    suspense()
    print("Press any key to continue.\n")
    msvcrt.getch()
    os.system("cls")
    long()
    scene2()

def scene1c():
    os.system("cls")
    narr()
    print("{Oh! I don't think it's good to be rebellious here.}\n")
    long()
    print("{Maybe I should just play along}")
    long()
    print("As you say sir...")
    long()
    print("Excuse Me, If I unknowingly caused you any inconvenience.\n")
    suspense()
    print("The Guardian Angel seems impressed.")
    global help
    help = help+1
    narr()
    print("You might get his help later if you keep him impressed.\n")
    narr()
    print("[Uhmm..]")
    narr()
    print("[Uhmm..]")
    long()
    print("[Enough of the flattery.]")
    long()
    print("[So I was telling you that]")
    quick()
    print("..clunk..")
    suspense()
    print("..creak..\n")
    narr()
    print("A door opens behind you")
    notice()
    print("You look back")
    narr()
    print("Press any key to continue..")
    msvcrt.getch()
    os.system("cls")
    long()
    scene2()

def scene1():
    os.system("cls")
    print("darkness",end="")
    dots()
    os.system("cls")
    time.sleep(0.85)
    print("THUD")
    long()
    print("You fall from your bed...")
    narr()
    print("You wake up and realise something",end=" ")
    narr()
    print("\"This is not my room.\"")
    long()
    print("You get up and notice something")
    notice()
    print("You are wearing a long brown coat")
    long()
    print("You check your pockets")
    long()
    dots()
    quick()
    print("You found a pen, a notebook, a badge.")
    long()
    print("Press e to interact with the badge")
    choice=msvcrt.getch().decode()
    if choice=="e":
        os.system("cls")
        time.sleep(0.45)
        print("You see the badge.")
        narr()
        print("The badge reads: Detective Mehul - Private Detective")
        long()
    else:
        print("You chose to ignore the badge.\n")
        long()
    
    print("\"What is this happening...\"\n")
    narr()
    print("A strange voice suddenly  fills the room.\n")
    narr()
    print("[Getting normal, are you?]")
    long()
    print("\"What!!\"\n")
    suspense()
    dots()
    dots()
    suspense()
    print("\"Is this game lagging\"\n")
    quick()
    print("[Absolutely Not!]")
    long()
    print("[Come on, It was just a dramatical pause.]")
    long()
    print("[By the way, treat me with some respect]")
    long()
    print("[I am your guardian angel.]\n")
    suspense()
    print("\"Am I dreaming..\"")
    quick()
    print("[Absolutely Not, You have been reincarnated as detective Mehul.]\n")
    suspense()
    print("\"Whatt!!, Why??")
    narr()
    print("[You really think you have a choice]\n")
    quick()
    print("\"Why don't I have one?\"")
    suspense()
    print("[Come on, Just Accept It.]\n\n")
    narr()
    print("Press any key to continue.")
    msvcrt.getch()
    print("Chose one Option: ")
    print("a) \"I really don't seem to have any choice...\"")
    print("b) \"How do you even think I am gonna agree to it...\"")
    print("c) \"As you say Sir...\"")
    time.sleep(0.25)
    ch1=msvcrt.getch().decode()
    while ch1!="a" and ch1!="b" and ch1!="c":
        print("Chose from the options(a,b,c).")
        time.sleep(0.15)
        ch1=msvcrt.getch().decode()
    
    if ch1=="a":
        long()
        scene1a()
    if ch1=="b":
        long()
        scene1b()
    if ch1=="c":
        long()
        scene1c()

scene2b()

